### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-DuilioAquino10#1]
[Sintesis2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-DuilioAquino10/files/9641861/Sintesis2.pdf)

**Comment by josealfredo79** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
